// <auto-generated />
using System;
using CinemaManagementSystem.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaManagementSystem.Persistence.Migrations
{
    [DbContext(typeof(CinemaManagementSystemDbContext))]
    [Migration("20230708062446_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Actor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5255d7fa-c966-4057-aa81-daaac393a4e4"),
                            BirthDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(2000),
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(2400),
                            Description = "Xinh gai, code gioi :))",
                            Gender = "Female",
                            ImageUrl = "",
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(2410),
                            Name = "Cao Quynh Anh"
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7a832a3-39d0-4bc5-aa25-ed884b9b589c"),
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(2940),
                            Description = "Founded in 1971, Lucasfilm is one of the world's leading entertainment companies and home to the legendary Star Wars and Indiana Jones franchises.",
                            ImageUrl = "/o86DbpburjxrqAzEDhXZcyE8pDb.png",
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(2940),
                            Name = "Lucasfilm Ltd."
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d55f1c00-98d2-4fd3-94ab-1be5f2d3cfd9"),
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(1560),
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(1560),
                            Name = "Phim Hành Động"
                        },
                        new
                        {
                            Id = new Guid("f7e1ac42-8902-4df3-ac25-d20c360586b2"),
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(1580),
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(1580),
                            Name = "Phim Phiêu Lưu"
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeRequired")
                        .HasColumnType("int");

                    b.Property<string>("BackDropUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e04dd7d-c209-4434-b8eb-64396ce0f8d9"),
                            AgeRequired = 8,
                            BackDropUrl = "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(1230),
                            Description = "Dom Toretto và gia đình anh ta là mục tiêu của đứa con trai đầy thù hận của trùm ma túy Hernan Reyes.",
                            ImageUrl = "/brZzXXQ8GuzlAdu4TJxjhC8ebBL.jpg",
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(1240),
                            ReleaseDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(1100),
                            Title = "Fast & Furious X"
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.MovieActor", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActor");

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("0e04dd7d-c209-4434-b8eb-64396ce0f8d9"),
                            ActorId = new Guid("5255d7fa-c966-4057-aa81-daaac393a4e4")
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.MovieCompany", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("MovieCompany");

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("0e04dd7d-c209-4434-b8eb-64396ce0f8d9"),
                            CompanyId = new Guid("e7a832a3-39d0-4bc5-aa25-ed884b9b589c")
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenre");

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("0e04dd7d-c209-4434-b8eb-64396ce0f8d9"),
                            GenreId = new Guid("d55f1c00-98d2-4fd3-94ab-1be5f2d3cfd9")
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Rate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1634490f-bed2-4060-b55d-ec9e95e6b25d"),
                            Comment = "Web xịn, phim hay, toàn trai xinh gái đẹp, recommend nha mọi ngừi",
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(4150),
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(4150),
                            MovieId = new Guid("0e04dd7d-c209-4434-b8eb-64396ce0f8d9"),
                            Rating = 9.5,
                            UserId = new Guid("00000001-0001-0001-0101-010101010101")
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasFilter("[CompanyId] IS NOT NULL");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0001-0001-0101-010101010101"),
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 757, DateTimeKind.Local).AddTicks(1300),
                            Firstname = "System",
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 765, DateTimeKind.Local).AddTicks(9860),
                            Lastname = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0002-0202-020202020202"),
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(170),
                            Firstname = "System",
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(170),
                            Lastname = "Publisher"
                        },
                        new
                        {
                            Id = new Guid("00000003-0003-0003-0303-030303030303"),
                            CreatedBy = "Administrator",
                            DateCreated = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(170),
                            Firstname = "System",
                            LastModifiedBy = "Administrator",
                            LastModifiedDate = new DateTime(2023, 7, 8, 13, 24, 45, 766, DateTimeKind.Local).AddTicks(180),
                            Lastname = "User"
                        });
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.MovieActor", b =>
                {
                    b.HasOne("CinemaManagementSystem.Domain.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagementSystem.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.MovieCompany", b =>
                {
                    b.HasOne("CinemaManagementSystem.Domain.Entities.Company", "Company")
                        .WithMany("MovieCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagementSystem.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieCompanies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.MovieGenre", b =>
                {
                    b.HasOne("CinemaManagementSystem.Domain.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagementSystem.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Rate", b =>
                {
                    b.HasOne("CinemaManagementSystem.Domain.Entities.Movie", "Movie")
                        .WithMany("Rates")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagementSystem.Domain.Entities.User", "User")
                        .WithMany("Rates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("CinemaManagementSystem.Domain.Entities.Company", "Company")
                        .WithOne("User")
                        .HasForeignKey("CinemaManagementSystem.Domain.Entities.User", "CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Company", b =>
                {
                    b.Navigation("MovieCompanies");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieCompanies");

                    b.Navigation("MovieGenres");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("CinemaManagementSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
